name: music_widget_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-123.0.dev

dependencies:
  flutter:
    sdk: flutter
  home_widget: ^0.7.0
  just_audio: ^0.9.42

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
